# Introduction to Functions

### Fibonacci in Python | Simple function

In [19]:
# The fibonacci series up to n | Simply print out the return 
def fib(n):
    a, b = 0, 1 #or we could've put a = 0 and then b = 1
    while a <n:
        print(a, end=' | ')
        a, b = b, a+b
    print()
    
#We just defined the Fibonacci function. 
# Now we can call it with a certain value of n


In [20]:
fib(100)

0 | 1 | 1 | 2 | 3 | 5 | 8 | 13 | 21 | 34 | 55 | 89 | 


In [21]:
fib(1000)

0 | 1 | 1 | 2 | 3 | 5 | 8 | 13 | 21 | 34 | 55 | 89 | 144 | 233 | 377 | 610 | 987 | 


In [22]:
# The fibonacci series up to n | Return a list containing the results. 
def fib2(n):
    result = []
    a, b = 0,1
    while a < n:
        result.append(a)
        a, b = b, a+b
    return result

In [23]:
# Let's call the new function
fib2(100)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

In [24]:
# Let's create a variable and store the result in it
fib100 = fib2(100)

In [25]:
fib100

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

### Function with one or more arguments 

In [26]:
# A fast food shop automatic reply | With a final formal parameter of the form **name
# **name which is a dictionary containing all keyword arguments except for those corresponding to a form *name.
# A formal parameter of the form *name is a tuple containing the positional arguments beyond the formal paramater list. 

In [28]:
def cheeseshop(kind, *arguments, **keywords):
    print("-- Do you have any", kind, "?")
    print("-- I'm sorry, we're all out of", kind)
    for arg in arguments:
        print(arg)
    print("-" *40)
    for kw in keywords:
        print(kw, ":", keywords[kw])

In [29]:
# Let's try
cheeseshop("Hamburger", "It's very runny, sir.", "It's really very, Very runny, sir.", shopkeeper= "Michael Palin", client="John Cleese", sketch="Cheese Shop Sketch")

-- Do you have any Hamburger ?
-- I'm sorry, we're all out of Hamburger
It's very runny, sir.
It's really very, Very runny, sir.
----------------------------------------
shopkeeper : Michael Palin
client : John Cleese
sketch : Cheese Shop Sketch


### The lambda expression

In [30]:
# It is a keyword used to create small anonymous functions. 
# they are syntactically restricted to a singlw expression

# Example 1: An incrementor
def make_incrementor(n):
    return lambda x: x + n
f = make_incrementor(28)

In [32]:
print(f(1))
print(f(3))
print(f(5))

29
31
33


In [37]:
# Example 2: Use lambda function to pass a small function as an argument

pairs = [(1,'one'), (2,'two'),(3, 'three'), (4, 'four')]
pairs.sort(key=lambda pair: pair[1])
pairs

[(4, 'four'), (1, 'one'), (3, 'three'), (2, 'two')]

## Universal Functions in Numpy

In [73]:
# Examples of ufunc
#------------------------------------------------------------------

#import NumPy library
import numpy as np


In [74]:
np_sqrt = np.sqrt([2,4,9,16, 45])

In [75]:
np_sqrt

array([1.41421356, 2.        , 3.        , 4.        , 6.70820393])

In [76]:
#We can also import predefined variable like pi
from numpy import pi
np.cos(0)

1.0

In [77]:
np.sin(pi/2)

1.0

In [78]:
np.cos(pi/4)

0.7071067811865476

In [79]:
np.cos(pi)

-1.0

In [80]:
#Floor of an input element
np.floor([1.5,1.6,2.7,3.3,1.1,-0.3,-1.4])

array([ 1.,  1.,  2.,  3.,  1., -1., -2.])

In [81]:
#Exponential functions for complex mathematical calculations
np.exp([0,1,5])

array([  1.        ,   2.71828183, 148.4131591 ])

### Shape Manipulation

#### Split | Flatten | Resize | Reshape | Stack

In [82]:
# Examples of manupulation of an array using the shape functions 

In [83]:
cyclist_trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])

In [84]:
cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [85]:
# Flatten the dataset - makes it one raw 
cyclist_trials.ravel()

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [86]:
#Change or reshape the dataset to many rows and/or columns
cyclist_trials.reshape(3,4) #3 rows and 4 columns here | remenber #elements = row*columns

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [87]:
cyclist_trials.reshape(2,6)

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [88]:
# Resize function will do the same work here but change the original dataset
cyclist_trials.resize(2,6)

In [89]:
cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [91]:
#Let's split the array into two
np.hsplit(cyclist_trials,2)

[array([[10, 15, 17],
        [12, 11, 21]]),
 array([[26, 13, 19],
        [24, 14, 23]])]

In [94]:
# Stacks two differents arrays together
new_cyclist_1 = np.array([10, 15, 17, 26, 13, 19])
new_cyclist_2 = np.array([12, 11, 21, 24, 14, 23])

In [96]:
np.hstack([new_cyclist_1,new_cyclist_2])

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

### Broadcasting

Broadcasting is used to carry out arithmetic operations between arrays of differents shapes. 

In [98]:
#Two arrays of the same shape
array_a = np.array([2,3,4,5])
array_b = np.array([0.4,0.4,0.4,0.4])

In [99]:
#Multiply arrays
array_a*array_b


array([0.8, 1.2, 1.6, 2. ])

In [100]:
#Broadcasting | Let's create a variable with a scalar value 
scalar_c = 0.4

In [102]:
array_a*scalar_c

array([0.8, 1.2, 1.6, 2. ])

### Linear Algebra - Transpose
Numpy can carry out linear algebraic functions as well. The 'transpose()' function can help you to interchange rows as columns and vice-versa

In [104]:
test_scores = np.array([[83,71,57,63],[54,68,81,45]])

In [105]:
test_scores.transpose()

array([[83, 54],
       [71, 68],
       [57, 81],
       [63, 45]])

In [107]:
# Inverse and Trace Functions
# Using Numpy, you can also find the inverse of an array and add its diagonal data elements.
inverse_array = np.array([[10,20],[15,25]])

# -------------------------------------------------------------

np.linalg.inv(inverse_array)


array([[-0.5,  0.4],
       [ 0.3, -0.2]])

In [109]:
trace_array = np.array([[10,20],[22,31]])

In [110]:
np.trace(trace_array)

41