In [9]:
#import NumPy library
import numpy as np


In [10]:
#first Numpy array
first_numpy_array = np.array([1,2,3,4,5])

In [12]:
#print first NumPy array
print(first_numpy_array)

[1 2 3 4 5]


In [13]:
#array with zeros
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
#array with ones
array_with_ones = np.ones((2,2))
array_with_ones

array([[1., 1.],
       [1., 1.]])

In [16]:
#array with empty
array_with_empty = np.empty((2,4))
array_with_empty

array([[ 1.28822975e-231, -4.33606417e-311,  1.97626258e-323,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  1.28822975e-231,
         5.60604529e-309]])

In [19]:
#array with arange method
np_arange =np.arange(12)

print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [20]:
#reshape method to change or create array
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
#linspace for linearly (equal)spaced data elements
#1st element = 1
#2sd element = 6
#total number or equidistant element = 5
np_linspace = np.linspace(1,6,5)
np_linspace

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [22]:
#one dimensional array
oneD_array = np.arange(15)
oneD_array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
twoD_array = oneD_array.reshape(3,5)
twoD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
#three dimensional array
threeD_array = np.arange(27).reshape(3,3,3)
threeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])