In [9]:
#import NumPy library
import numpy as np


In [10]:
#first Numpy array
first_numpy_array = np.array([1,2,3,4,5])

In [12]:
#print first NumPy array
print(first_numpy_array)

[1 2 3 4 5]


In [13]:
#array with zeros
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
#array with ones
array_with_ones = np.ones((2,2))
array_with_ones

array([[1., 1.],
       [1., 1.]])

In [16]:
#array with empty
array_with_empty = np.empty((2,4))
array_with_empty

array([[ 1.28822975e-231, -4.33606417e-311,  1.97626258e-323,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  1.28822975e-231,
         5.60604529e-309]])

In [19]:
#array with arange method
np_arange =np.arange(12)

print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [20]:
#reshape method to change or create array
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
#linspace for linearly (equal)spaced data elements
#1st element = 1
#2sd element = 6
#total number or equidistant element = 5
np_linspace = np.linspace(1,6,5)
np_linspace

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [22]:
#one dimensional array
oneD_array = np.arange(15)
oneD_array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
twoD_array = oneD_array.reshape(3,5)
twoD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
#three dimensional array
threeD_array = np.arange(27).reshape(3,3,3)
threeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [26]:
print(np.linspace(4,13,7))

[ 4.   5.5  7.   8.5 10.  11.5 13. ]


In [27]:
#Basics Operations with NumPy
#Mathematical Operations
#.........
#Addition
np.add(45,20)

65

In [29]:
#substraction
np.subtract(2020,1995)

25

In [30]:
#ndarray multiplication
#create ndarray which contains number of hrs worked for 5days

#......hourly rate is 15 USD
np_daily_hour = np.array([7,9,13,8,11])
np_daily_wage = np_daily_hour*15
np_daily_wage

array([105, 135, 195, 120, 165])

In [32]:
#Total weekly earnings
sum(np_daily_wage)

720

In [33]:
#COMPARISONS Operations
np_weekly_hours = np.array([40,23,25,36,45,40])
#Week with more than 37h shifts
np_weekly_hours[np_weekly_hours>37]

array([40, 45, 40])

In [34]:
#week with more not equal to 40h
np_weekly_hours[np_weekly_hours != 40]

array([23, 25, 36, 45])

In [36]:
#LOGICAL Operations
#logical AND operation
np.logical_and(np_weekly_hours>20, np_weekly_hours<35)

array([False,  True,  True, False, False, False])

In [41]:
#logical NO operation
np.logical_not(np_weekly_hours>25)

array([False,  True,  True, False, False, False])